In [18]:
import pandas as pd
import matplotlib.pyplot as plt

shopping_data = pd.read_csv("processed/shopping_cleaned.csv")

df = pd.read_csv('../data/raw/shopping.csv')

In [10]:
shopping_data.head()

,Age,Gender,Item Purchased,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Shipping Type,Promo Code Used,Previous Purchases,Payment Method
0,31.0,Male,Leggings,24.231704,Nevada,M,Terra cotta,Winter,Present,Standard,No,0,Credit Card
1,38.0,Male,Sunglasses,36.545487,Oregon,S,Aubergine,Summer,Missing,Standard,No,0,Credit Card
2,26.0,Male,Leggings,23.595139,Nevada,XL,Brown,Winter,Missing,Standard,No,3,Credit Card
3,43.0,Male,Dress,34.079015,California,M,Terra cotta,Fall,Present,Standard,No,0,Credit Card
4,29.0,Male,Shorts,23.796439,Minnesota,M,Lavender,Summer,Present,Express,No,0,Credit Card

In [12]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3510.000000,3900.000000,1431.000000,3900.000000
mean,1950.500000,34.256695,38.708329,3.904962,5.841538
std,1125.977353,10.616340,11.504923,1.105952,5.843695
min,1.000000,18.000000,11.392520,1.000000,0.000000
25%,975.750000,26.000000,29.332617,4.000000,1.000000
50%,1950.500000,33.000000,36.953004,4.000000,4.000000
75%,2925.250000,41.000000,48.739596,5.000000,9.000000
max,3900.000000,75.000000,69.567481,5.000000,20.000000

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3510 non-null   float64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Purchase Amount (USD)   3900 non-null   float64
 5   Location                3510 non-null   str
 6   Size                    3900 non-null   str
 7   Color                   3900 non-null   str
 8   Season                  3900 non-null   str
 9   Review Rating           1431 non-null   float64
 10  Shipping Type           3900 non-null   str
 11  Promo Code Used         3900 non-null   str
 12  Previous Purchases      3900 non-null   int64
 13  Payment Method          3900 non-null   str
 14  Frequency of Purchases  1560 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 457.2 KB

In [14]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3510.000000,3900.000000,1431.000000,3900.000000
mean,1950.500000,34.256695,38.708329,3.904962,5.841538
std,1125.977353,10.616340,11.504923,1.105952,5.843695
min,1.000000,18.000000,11.392520,1.000000,0.000000
25%,975.750000,26.000000,29.332617,4.000000,1.000000
50%,1950.500000,33.000000,36.953004,4.000000,4.000000
75%,2925.250000,41.000000,48.739596,5.000000,9.000000
max,3900.000000,75.000000,69.567481,5.000000,20.000000

In [ ]:
shopping_data['Payment Method'].unique()

1. What is the ratio of male to female who purchased items?
There are 1579 males to 1550 females who purchased items. Though there are more males who shopped, the purchased amounts are close in margin.

In [49]:
shopping_data.groupby('Gender')['Item Purchased'].count()

Gender
Female        1550
Male          1579
Non-binary      29
Name: Item Purchased, dtype: int64

2. Which age group had the most overall orders?
The adult age group, ages 30 to 50, had the most overall orders.

In [61]:
shopping_data['age_group'] = pd.cut( df['Age'], bins=[0, 18, 30, 50, 100], labels=['Child', 'Young Adult', 'Adult', 'Senior'] )

shopping_data.groupby('age_group')['Item Purchased'].count()

age_group
Child            64
Young Adult    1094
Adult          1452
Senior          223
Name: Item Purchased, dtype: int64

3. Which season experienced more purchases per state?
Alabama: Winter
Alaska:  Fall
Arizona: Winter
Arkansas: Winter
California: Winter 
Colorado: Winter  
Connecticut: Winter
Delaware: Winter
Florida: Winter  
Georgia: Fall 
Hawaii: Fall   
Idaho: Winter  
Illinois: Winter       
Indiana: Winter        
Iowa: Fall             
Kansas: Winter        
Kentucky: Winter      
Louisiana: Fall     
Maine: Winter           
Maryland: Winter        
Massachusetts: Winter    
Michigan: Fall         
Minnesota: Winter    
Mississippi: Winter   
Missouri: Winter       
Montana: Fall        
Nebraska: Winter        
Nevada: Winter       
New Hampshire: Winter   
New Jersey: Fall     
New Mexico: Fall     
New York: Winter             
North Carolina: Winter   
North Dakota: Fall   
Ohio: Winter             
Oklahoma: Winter        
Oregon: Winter         
Pennsylvania: Fall    
Rhode Island: Winter     
South Carolina:  Winter 
South Dakota: Winter    
Tennessee: Winter       
Texas: Winter           
Utah: Winter           
Vermont: Fall        
Virginia:Winter         
Washington: Fall and Winter        
West Virginia: Winter    
Wisconsin: Spring       
Wyoming: Fall

In [ ]:
shopping_data.pivot_table(index= 'Location', columns='Season', aggfunc= 'size').reset_index()

In [ ]:
# Just verifying that the above numbers match per location 
shopping_data.groupby('Location')['Purchase Amount (USD)'].count()

4. Which method of payment is most used overall?
Credit card usage overall is the most used payment method in this data set.

In [ ]:
shopping_data.groupby('Payment Method')['Item Purchased'].count()

Required Analytical Questions:

1. What are the most popular colors by season?
For the Fall, brown is the most popular color, spring: baby blue, summer: lavender, and winter: black.

In [78]:
shopping_data.groupby('Season')['Color'].agg(pd.Series.mode).apply(lambda x: x[0] if isinstance(x, list) else x)

Season
Fall          Brown
Spring    Baby blue
Summer     Lavender
Winter        Black
Name: Color, dtype: str

2. What is the most popular clothing item by season?
Here are the most popular clothing item by season:
For Fall, it is both backpack and sweater, spring: running shoes, summer: shorts, and winter, it is leggings.

In [79]:
shopping_data.groupby('Season')['Item Purchased'].agg(pd.Series.mode).apply(lambda x: x[0] if isinstance(x, list) else x)

Season
Fall      [Backpack, Sweater]
Spring          Running Shoes
Summer                 Shorts
Winter               Leggings
Name: Item Purchased, dtype: object

3. What is the effect of promo codes on the dollar amount of purchases?
It seems like the promo code did not make much of a difference in the dollar amount of purchases and so there are less people using the promo code to make purchases.

In [99]:
shopping_data.groupby('Promo Code Used')['Purchase Amount (USD)'].size()

Promo Code Used
No     1785
Yes    1373
Name: Purchase Amount (USD), dtype: int64

4. When do users leave a review?
From this analysis, users seem to leave a review more when they do not use a promo code.

In [93]:
shopping_data.pivot_table(values= 'Previous Purchases', index= 'Promo Code Used', columns='Review Rating', aggfunc= 'size')

Review Rating    Missing  Present
Promo Code Used
No                  1129      656
Yes                  891      482